#!/bin/bash
#                                                                  mk Jan 2013
# Script to extract and colllate data from MainJob_dir  
# -----------------------------------------------------------------------------
# This will create loader files to read in sequential namd dcd runs 
# with a single script.
#
source ../Scripts/common_functions.sh

#-- create a local version of a dcd_loader file: 
combined="combined_dcd_loader_script"

#-- make a temporary data directory: 
[[ -d temp_data_dir ]] && rm -rf temp_data_dir
mkdir -p temp_data_dir

for f in dcdfile_list_*.txt; do
  [[ -f $f ]] && rm $f
done

#-- write header to file: 
echo "#!/usr/local/bin/vmd " >$combined.vmd
echo "# VMD script written by save_state $Revision: 1.44 $" >>$combined.vmd
echo "# VMD version: 1.9.1" >>$combined.vmd

# -- Source master_config_file: -----------------------------------------------
read_master_config_file ../Setup_and_Config

# -- create basic vmd input setup file:
echo "#!/usr/local/bin/vmd " >basic_vmd_setup.vmd
echo "# VMD script written by save_state $Revision: 1.44 $" >>basic_vmd_setup.vmd
echo "# VMD version: 1.9.1" >>basic_vmd_setup.vmd

# -- grab input psf and pdb files to create a basic vmd setup file. 
# -- assuming psf and pdb file reside in /InputFiles  (ignore change_me dummy files)
# -- prone to error -must check resultant setup file. 

psf_f=$( ls ../InputFiles/ | grep psf |grep -v change_me)   
pdb_f=$( ls ../InputFiles/ | grep pdb |grep -v change_me) 

echo "Date: `date`     " >> summary.txt
echo "Input psf: $psf_f" >> summary.txt
echo "Input pdb: $pdb_f" >> summary.txt

printf "mol new ../InputFiles/%s type psf first 0 last -1 step 1 filebonds 1 autobonds 1 waitfor all\n" $psf_f >>basic_vmd_setup.vmd
printf "mol addfile ../InputFiles/%s type pdb first 0 last -1 step 1 filebonds 1 autobonds 1 waitfor all\n" $pdb_f >>basic_vmd_setup.vmd 

# change to main job directory: 
cd ../

# --Check for existing directories under /MainJob_dir and grab "official" directory list. 

if [[ -d $JOB_DIR ]]; then

  # source directory list. 
  y=$(cat .dir_list.txt) 

  cd $JOB_DIR

  for i in $y
  do
    # --Extract dcd file locations into /CollectiveData/dcd_job_loader_file.vmd
    cd $i
    index=`echo $i | sed 's/.*_//'`

    # grab directory name
    echo -e " Extracting dcd file details in directory $JOB_DIR/$i \n "
    ../../Scripts/Analysis_Scripts/create_dcd_loader_script 

    # merge files: 
    cat OutputFiles/local_dcd_file_loader.vmd  >> ../../Analysis/${combined}_${index}.vmd
    cat OutputFiles/dcdfile_list.txt  >> ../../Analysis/dcdfile_list_${index}.txt
    rm OutputFiles/dcdfile_list.txt
    cd ../

  done
fi

echo -e " Extracted locations of dcd files from the /MainJob_dir in $combined.vmd" 
echo -e " Setup files written to basic_vmd_setup.vmd " 
echo -e " Make sure to check basic_vmd_setup.vmd is pointing to the right files! " 

cd ../Analysis
